version: "3.1"

services:
  reverse_proxy:
    image: itisenricofermi/archivio-digitale-stack:latest
    ports:
      - 3010:80
    depends_on:
      - backend
      - frontend
    deploy:
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: any
    networks:
      - backend-network
      - frontend-network

  frontend:
    image: itisenricofermi/archivio-digitale-client:latest
    deploy:
      placement:
        constraints: [node.role == manager]
      replicas: 2
      restart_policy:
        condition: any
    ports:
      - 3011:80
    depends_on:
      - backend
    networks:
      - frontend-network

  backend:
    image: itisenricofermi/archivio-digitale-server:latest
    deploy:
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: any
    secrets:
      - server_jwt_secret
      - minio_access_key
      - minio_secret_key
    ports:
      - 3012:80
    environment:
      - "MONGODB_URI=mongodb://database:27017/archivio"
      - "MAILER_URL=http://mailer/send"
      - MINIO_HOST=minio
      - MINIO_PORT=9000
      - MINIO_SECRET_KEY_FILE=/run/secrets/minio_secret_key
      - MINIO_ACCESS_KEY_FILE=/run/secrets/minio_access_key
      - JWT_SECRET_FILE=/run/secrets/server_jwt_secret
    depends_on:
      - database
      - minio
    networks:
      - backend-network
      - frontend-network

  database:
    image: mongo:3.4.19-jessie
    ports:
      - 27017:27017
    deploy:
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: any
    volumes:
      - database-data:/data/db
      - database-config:/data/configdb
    environment:
      - MONGO_INITDB_DATABASE=archivio
    networks:
      - backend-network

  mailer:
    image: itisenricofermi/archivio-digitale-mailer:latest
    deploy:
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: any
    secrets:
      - mailer_user
      - mailer_password
      - mailer_json_key
    environment:
      - USER_FILE=/run/secrets/mailer_user
      - PASSWORD_FILE=/run/secrets/mailer_password
      - JSON_SECRET=/run/secrets/mailer_json_key
      - SECURE=0
      - PORT=587
      - SERVER=smtp.gmail.com
      - FROM=admin@archivio.itisfermi.edu.it
    networks:
      - backend-network

  minio:
    image: minio/minio:RELEASE.2019-04-04T18-31-46Z
    deploy:
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: any
    command: server /data
    volumes:
      - minio-data:/data
      - minio-config:/root/.minio
    secrets:
      - minio_secret_key
      - minio_access_key
    environment:
      - MINIO_SECRET_KEY_FILE=minio_secret_key
      - MINIO_ACCESS_KEY_FILE=minio_access_key
    networks:
      - backend-network
    ports:
      - 3013:9000

secrets:
  minio_secret_key:
    file: minio-sk.txt
  minio_access_key:
    file: minio-ak.txt
  server_jwt_secret:
    file: server-secret.txt
  mailer_user:
    file: mailer-user.txt
  mailer_password:
    file: mailer-pass.txt
  mailer_json_key:
    file: key.json

networks:
  frontend-network:
  backend-network:

volumes:
  database-data:
  database-config:
  minio-data:
  minio-config: