version: "3.1"

services:
  reverse_proxy:
    image: itisenricofermi/archivio-digitale-stack:latest
    ports:
      - 3010:80
    depends_on:
      - backend
      - frontend
    deploy:
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: any
    networks:
      - backend-network
      - frontend-network

  frontend:
    image: itisenricofermi/archivio-digitale-client:latest
    deploy:
      placement:
        constraints: [node.role == manager]
      replicas: 2
      restart_policy:
        condition: any
    depends_on:
      - backend
    networks:
      - frontend-network

  backend:
    image: itisenricofermi/archivio-digitale-server:latest
    deploy:
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: any
    secrets:
      - archivio_server_jwt_secret
      - archivio_minio_access_key
      - archivio_minio_secret_key
    environment:
      - "MONGODB_URI=mongodb://database:27017/archivio"
      - "MAILER_URL=http://mailer/send"
      - MINIO_HOST=minio
      - MINIO_PORT=9000
      - MINIO_SECRET_KEY_FILE=/run/secrets/archivio_minio_secret_key #test key
      - MINIO_ACCESS_KEY_FILE=/run/secrets/archivio_minio_access_key #test key
      - UPDATER_URL=updater
      - UPDATER_PORT=3050
      - JWT_SECRET_FILE=/run/secrets/archivio_server_jwt_secret
    depends_on:
      - database
      - minio
    networks:
      - backend-network
      - frontend-network

  database:
    image: mongo:3.4.19-jessie
    deploy:
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: any
    volumes:
      - database-data:/data/db
      - database-config:/data/configdb
    environment:
      - MONGO_INITDB_DATABASE=archivio
    networks:
      - backend-network

  mailer:
    image: itisenricofermi/archivio-digitale-mailer:latest
    deploy:
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: any
    secrets:
      - archivio_mailer_user
      - archivio_mailer_password
    environment:
      - USER_FILE=/run/secrets/archivio_mailer_user
      - PASSWORD_FILE=/run/secrets/archivio_mailer_password
      - SERVER=smtp.ionos.com
      - FROM=me@riccardosangiorgio.com
    networks:
      - backend-network

  updater:
    image: prons/archivio-digitale-updater:latest
    deploy:
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: any
    networks: 
      - backend-network

  minio:
    image: minio/minio:RELEASE.2019-04-04T18-31-46Z
    deploy:
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: any
    command: server /data
    volumes:
      - minio-data:/data
      - minio-config:/root/.minio
    secrets:
      - archivio_minio_secret_key
      - archivio_minio_access_key
    environment:
      - MINIO_SECRET_KEY_FILE=archivio_minio_secret_key #test key
      - MINIO_ACCESS_KEY_FILE=archivio_minio_access_key #test key
    networks:
      - backend-network
    ports:
      - 3333:9000

secrets:
  archivio_minio_secret_key:
    external: true
  archivio_minio_access_key:
    external: true
  archivio_server_jwt_secret:
    external: true
  archivio_mailer_user:
    external: true
  archivio_mailer_password:
    external: true

networks:
  frontend-network:
    driver: overlay
  backend-network:
    driver: overlay
    
volumes:
  database-data:
  database-config:
  minio-data:
  minio-config:
