version: "3.1"

services:
  reverse_proxy:
    image: itisenricofermi/archivio-digitale-stack:latest
    ports:
      - 3010:80
    depends_on:
      - backend
      - frontend
    deploy:
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: any
    networks:
      - backend-network
      - frontend-network

  frontend:
    image: itisenricofermi/archivio-digitale-client:latest
    deploy:
      placement:
        constraints: [node.role == manager]
      replicas: 2
      restart_policy:
        condition: any
    depends_on:
      - backend
    networks:
      - frontend-network
    ports:
      - 3011:80

  backend:
    image: itisenricofermi/archivio-digitale-server:latest
    deploy:
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: any
    secrets:
      - archivio_server_jwt_secret
      - archivio_minio_access_key
      - archivio_minio_secret_key
    environment:
      - "MONGODB_URI=mongodb://database:27017/archivio"
      - "MAILER_URL=http://mailer/send"
      - MINIO_HOST=minio
      - MINIO_PORT=9000
      - MINIO_ACCESS_KEY=/run/secrets/archivio_minio_access_key
      - MINIO_SECRET_KEY=/run/secrets/archivio_minio_secret_key
      - JWT_SECRET_FILE=/run/secrets/archivio_server_jwt_secret
      - "UPDATER_URL=http://updater/"
      - UPDATER_TOKEN_FILE=/run/secrets/archivio_updater_token
      - NODE_ENV=development
    depends_on:
      - database
      - minio
    networks:
      - backend-network
      - frontend-network
    ports:
      - 3012:80

  database:
    image: mongo:3.4.19-jessie
    deploy:
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: any
    volumes:
      - database-data:/data/db
      - database-config:/data/configdb
    environment:
      MONGO_INITDB_DATABASE: archivio
    ports:
      - 27017:27017
    networks:
      - backend-network

  mailer:
    image: itisenricofermi/archivio-digitale-mailer:latest
    deploy:
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: any
    secrets:
      - archivio_mailer_user
      - archivio_mailer_password
    environment:
      - USER_FILE=/run/secrets/archivio_mailer_user
      - PASSWORD_FILE=/run/secrets/archivio_mailer_password
      - SERVER=smtp.ionos.com
      - FROM=me@riccardosangiorgio.com
    networks:
      - backend-network

  updater:
    image: prons/archivio-digitale-updater:2.1.1
    deploy:
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: any
    networks: 
      - backend-network
    environment:
      - NODE_ENV=development
      - TOKEN_FILE=/run/secrets/archivio_updater_token
    ports: 
      - 3050:80
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock:ro

  minio:
    image: minio/minio:RELEASE.2019-04-04T18-31-46Z
    deploy:
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: any
    command: server /data
    volumes:
      - minio-data:/data
      - minio-config:/root/.minio
      # - ./minio/data:/data
      # - ./minio/config:/root/.minio
    secrets:
      - archivio_minio_secret_key
      - archivio_minio_access_key
    environment:
      - MINIO_SECRET_KEY_FILE=archivio_minio_secret_key #test key
      - MINIO_ACCESS_KEY_FILE=archivio_minio_access_key #test key
    ports:
      - 3013:9000 # Remove me in production
    networks:
      - backend-network

secrets:
  archivio_minio_secret_key:
    file: minio-sk.txt
  archivio_minio_access_key:
    file: minio-ak.txt
  archivio_server_jwt_secret:
    file: server-secret.txt
  archivio_mailer_user:
    file: mailer-user.txt
  archivio_mailer_password:
    file: mailer-pass.txt
  archivio_updater_token:
    file: updater-token.txt

networks:
  frontend-network:
  backend-network:

volumes:
  database-data:
  database-config:
  minio-data:
  minio-config:
