version: "3.1"

services:
  reverse_proxy:
    image: itisenricofermi/archivio-digitale-stack:latest
    ports:
      - 3010:80
    depends_on:
      - backend
      - frontend
    deploy:
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: any
    networks:
      - backend-network
      - frontend-network

  frontend:
    image: itisenricofermi/archivio-digitale-client:latest
    deploy:
      placement:
        constraints: [node.role == manager]
      replicas: 2
      restart_policy:
        condition: any
    depends_on:
      - backend
    networks:
      - frontend-network

  backend:
    image: itisenricofermi/archivio-digitale-server:latest
    deploy:
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: any
    secrets:
      - server_jwt_secret
      - minio_access_key
      - minio_secret_key
    environment:
      - "MONGODB_URI=mongodb://database:27017/archivio"
      - "MAILER_URL=http://mailer/send"
      - MINIO_HOST=minio
      - MINIO_PORT=9000
      - MINIO_SECRET_KEY_FILE=/run/secrets/minio_secret_key #test key
      - MINIO_ACCESS_KEY_FILE=/run/secrets/minio_access_key #test key
      # - "UPDATER_URL=http://updater/"
      # - UPDATER_TOKEN_FILE=/run/secrets/updater_token
      - JWT_SECRET_FILE=/run/secrets/server_jwt_secret
    depends_on:
      - database
      - minio
    networks:
      - backend-network
      - frontend-network

  database:
    image: mongo:3.4.19-jessie
    deploy:
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: any
    volumes:
      - database-data:/data/db
      - database-config:/data/configdb
    environment:
      - MONGO_INITDB_DATABASE=archivio
    networks:
      - backend-network

  mailer:
    image: itisenricofermi/archivio-digitale-mailer:latest
    deploy:
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: any
    secrets:
      - mailer_user
      - mailer_password
    environment:
      - USER_FILE=/run/secrets/mailer_user
      - PASSWORD_FILE=/run/secrets/mailer_password
      - SECURE=true
      - PORT=465
      - SERVER=smtp.gmail.com
      - FROM=admin@archivio.itisfermi.edu.it
    networks:
      - backend-network

  # updater:
  #   image: prons/archivio-digitale-updater:2.1.1
  #   deploy:
  #     placement:
  #       constraints: [node.role == manager]
  #     restart_policy:
  #       condition: any
  #   networks: 
  #     - backend-network
  #   environment: 
  #     - TOKEN_FILE=/run/secrets/updater_token
  #   volumes: 
  #     - /var/run/docker.sock:/var/run/docker.sock:ro

  minio:
    image: minio/minio:RELEASE.2019-04-04T18-31-46Z
    deploy:
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: any
    command: server /data
    volumes:
      - minio-data:/data
      - minio-config:/root/.minio
    secrets:
      - minio_secret_key
      - minio_access_key
    environment:
      - MINIO_SECRET_KEY_FILE=minio_secret_key #test key
      - MINIO_ACCESS_KEY_FILE=minio_access_key #test key
    networks:
      - backend-network
    ports:
      - 3333:9000

secrets:
  minio_secret_key:
    external: true
  minio_access_key:
    external: true
  server_jwt_secret:
    external: true
  mailer_user:
    external: true
  mailer_password:
    external: true
  # updater_token:
  #   external: true

networks:
  frontend-network:
    driver: overlay
  backend-network:
    driver: overlay
    
volumes:
  database-data:
    external: true
  database-config:
    external: true
  minio-data:
    external: true
  minio-config:
    external: true
