apiVersion: v1
kind: Service
metadata:
  name: archivio-digitale-mailer-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    archivio-digitale: mailer
  ports:
    - port: 80
      targetPort: 80