apiVersion: apps/v1
kind: Deployment
metadata:
  name: archivio-digitale-minio-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      archivio-digitale: minio
  template:
    metadata:
      labels:
        archivio-digitale: minio
    spec:
      containers:
        - name: minio
          image: minio/minio:RELEASE.2019-04-04T18-31-46Z
          ports:
            - containerPort: 9000