apiVersion: v1
kind: Service
metadata:
  name: archivio-digitale-minio-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    archivio-digitale: minio
  ports:
    - port: 9000
      targetPort: 9000