apiVersion: apps/v1
kind: Deployment
metadata:
  name: archivio-digitale-minio-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      archivio-digitale: minio
  template:
    metadata:
      labels:
        archivio-digitale: minio
    spec:
      volumes:
        - name: archivio-digitale-minio-persistent-volume
          persistentVolumeClaim:
            claimName: archivio-digitale-minio-persistent-volume-claim
      containers:
        - name: minio
          image: minio/minio:RELEASE.2019-04-04T18-31-46Z
          command: ["server", "/data"]
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: archivio-digitale-minio-persistent-volume
              mountPath: /data
              subPath: data
            - name: archivio-digitale-minio-persistent-volume
              mountPath: /root/.minio
              subPath: config
          env:
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-secret-key
                  key: MINIO_SECRET_KEY
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-access-key
                  key: MINIO_ACCESS_KEY
