apiVersion: apps/v1
kind: Deployment
metadata:
  name: archivio-digitale-minio-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      archivio-digitale: minio
  template:
    metadata:
      labels:
        archivio-digitale: minio
    spec:
      volumes:
        - name: archivio-digitale-minio-persistent-volume
          persistentVolumeClaim:
            claimName: archivio-digitale-minio-persistent-volume-claim
      containers:
        - name: minio
          image: minio/minio:RELEASE.2019-04-04T18-31-46Z
          command:
            - server
          args:
            - /data
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: archivio-digitale-minio-persistent-volume
              mountPath: /data
              subPath: data
            - name: archivio-digitale-minio-persistent-volume
              mountPath: /root/.minio
              subPath: config