apiVersion: apps/v1
kind: Deployment
metadata:
  name: archivio-digitale-mongo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      archivio-digitale: mongo
  template:
    metadata:
      labels:
        archivio-digitale: mongo
    spec:
      volumes:
        - name: archivio-digitale-mongo-persistent-volume
          persistentVolumeClaim:
            claimName: archivio-digitale-mongo-persistent-volume-claim
      containers:
        - name: mongo
          image: mongo:3.4.19-jessie
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_DATABASE
              value: archivio
          volumeMounts:
            - name: archivio-digitale-mongo-persistent-volume
              mountPath: /data/db
              subPath: data
            - name: archivio-digitale-mongo-persistent-volume
              mountPath: /data/configdb
              subPath: config