apiVersion: v1
kind: Service
metadata:
  name: archivio-digitale-mongo-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    archivio-digitale: mongo
  ports:
    - port: 27017
      targetPort: 27017