apiVersion: v1
kind: Service
metadata:
  name: archivio-digitale-server-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    archivio-digitale: server
  ports:
    - port: 80
      targetPort: 80